### ISSUE TITLE
.ldrc is blank

### ISSUE THREAD

**Issue by michaelnagy** [aam229/local-dependencies#3]
Every time I use the configure-local-dependencies the generated .ldrc file is being generated as a blank file.

Can you give us an example of a manual configuration of this file?

**Comment by michaelnagy** [comment]
My bad, I was not selecting the package in the cli wizard, therefore the generated .ldrc was obviously blank.

Anyway, this is an example of the .ldrc file, in case someone needs it:

`{
  "package-name": {
    "path": "/path/to/local/package",
    "watch": true
  }
}`

**Comment by aam229** [comment]
I'm going to add a sample `.ldrc` to the README in case it helps someone down the road. I'm glad you also posted your fix. Do you think it's worth adding a section to the README describing how to use `configure-local-dependencies`?

**Comment by michaelnagy** [comment]
@aam229 Yes I think it's a good thing to do :)

**Comment by aam229** [comment]
Ok, I opened #4
